// Writes src/highlight-colors.css: the keyword highlight colours, from the official Radix Colors scales
// (@radix-ui/colors, the colour system behind shadcn). Run `pnpm colors` after changing the list below.
//
// Each colour has a light and a dark scale with the same 12 steps; we keep the steps the highlights use
// (3–5 backgrounds, 7–8 borders and rings, 9 solid, 12 text) as --rx-<colour>-<step>, the light ones on
// :root and the dark ones on .dark (the class the theme toggle sets), plus each colour's card ring.
import fs from "node:fs"
import path from "node:path"

import * as radix from "@radix-ui/colors"

import { HIGHLIGHT_COLORS } from "../src/lib/highlight-colors.ts"
import { ROOT } from "./lib/profiles.ts"

const STEPS = [3, 4, 5, 7, 8, 9, 12]
const scales = radix as unknown as Record<string, Record<string, string>>

/** "#0090ff" at `alpha` → "#0090ff73" */
const withAlpha = (hex: string, alpha: number) => `${hex}${Math.round(alpha * 255).toString(16).padStart(2, "0")}`

function block(selector: string, dark: boolean) {
  const lines = HIGHLIGHT_COLORS.flatMap((name) => {
    const scale = scales[dark ? `${name}Dark` : name]
    if (!scale) throw new Error(`@radix-ui/colors has no ${name} scale`)
    const step = (n: number) => scale[`${name}${n}`]
    // the matching card's ring: strong and soft, for its slow pulse (src/lib/keywords.ts)
    const ring = dark
      ? `0 0 0 1.5px ${step(8)}, 0 0 16px ${withAlpha(step(9), 0.45)}`
      : `0 0 0 2px ${step(8)}, 0 0 0 5px ${step(4)}`
    const soft = dark ? `0 0 0 1px ${step(7)}, 0 0 8px ${withAlpha(step(9), 0.2)}` : `0 0 0 1.5px ${step(7)}, 0 0 0 3px ${step(3)}`
    return [
      ...STEPS.map((n) => `  --rx-${name}-${n}: ${step(n)};`),
      `  --rx-${name}-ring: ${ring};`,
      `  --rx-${name}-ring-soft: ${soft};`,
    ]
  })
  return `${selector} {\n${lines.join("\n")}\n}`
}

const css = `/* Generated by scripts/build-highlight-colors.ts from @radix-ui/colors; don't edit by hand. */
${block(":root", false)}

${block(".dark", true)}
`
fs.writeFileSync(path.join(ROOT, "src/highlight-colors.css"), css)
console.log(`✓ ${HIGHLIGHT_COLORS.length} highlight colours written to src/highlight-colors.css`)
